# Harmony Jekyll theme general configurations 

# Site live URL
url: https://mrcosta.github.io

# Localhost 
#url: http://127.0.0.1:4000

disqus_shortname: mateuscosta

future: true

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Mateus Costa
  description:
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: > # 
   Harmony is a free responsive jekyll theme by Gayan Virajith
   and Maheshika Lakmali. Sourced on Github - 
   https://github.com/gayanvirajith/harmony
  basetheme: theme-base-01 # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Gayan Virajith
    email: gayanvirajith@gmail.com
    url: http://gayanvirajith.github.io

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-101987759-1

  # Profile links, leave blank to ignore
  social: 
    github: mrcosta

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: rouge 

# Permalinks
permalink:        pretty

exclude: 
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor
  - docker-compose.yml
  - frontmatter.json
  - .frontmatter

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
