services:
  jekyll-server:
    image: jekyll/jekyll:4.2.2
    volumes:
      - .:/srv/jekyll:Z
      - ./vendor/bundle:/usr/local/bundle:Z # cache for offline work
    ports:
      - "4000:4000" # server port
      - "35729:35729" # livereload port
    command: jekyll serve # runs jekyll local server
    # ↑ --drafts --livereload --incremental   you can add optional arguments